language: node_js
notifications:
  email: false
node_js:
  - '9'
  - '8'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
cache:
  directories:
  - "$HOME/.npm"
after_success:
  - npx nyc report --reporter=lcov | npx codecov
  - npm run cov:check
  - npm run doc
  - npm run doc:publish 
  - npm run travis-deploy-once "npm run semantic-release"